### ISSUE TITLE
Cannot build after ioctl.cr 1.0.0

### ISSUE THREAD

**Issue by soya-daizu** [postmodern/v4l2.cr#1]
The breaking change in ioctl.cr 1.0.0 causes v4l2.cr to fail building:

```
In lib/v4l2/src/linux/videodev2.cr:2263:30

 2263 | VIDIOC_S_FMT                       = ioctl_iowr('V',  5, V4L2Format)
                                   ^---------
Error: undefined fun 'ioctl_iowr' for Linux
```

I was able to build my program when I explicitly install the previous version of ioctl.cr, but then it fails at runtime with a memory allocation error:

```
VIDIOC_QBUF: Cannot allocate memory
        lib/v4l2/src/v4l2/device.cr:316:9 in 'enqueue_buffer'
        lib/v4l2/src/v4l2/device.cr:343:7 in 'enqueue_buffer'
        lib/v4l2/src/v4l2/buffer_queue.cr:39:7 in 'enqueue'
        lib/v4l2/src/v4l2/stream.cr:195:11 in 'start_capturing!'
        lib/v4l2/src/v4l2/stream.cr:221:9 in '__crystal_main'
        /home/soya_daizu/.asdf/installs/crystal/1.7.3/share/crystal/src/crystal/main.cr:115:5 in 'main_user_code'
        /home/soya_daizu/.asdf/installs/crystal/1.7.3/share/crystal/src/crystal/main.cr:101:7 in 'main'
        /home/soya_daizu/.asdf/installs/crystal/1.7.3/share/crystal/src/crystal/main.cr:127:3 in 'main'
        /usr/lib/libc.so.6 in '??'
        /usr/lib/libc.so.6 in '__libc_start_main'
        ./bin/goishi_gtk in '_start'
        ???
```

**Comment by postmodern** [comment]
I fixed the `ioctl` dependency in `shard.yml` which was causing it to use `1.0.0`. I'll have to update the code to use the new `ioctl` methods (they used to be macros, but were ported to methods).

**Comment by soya-daizu** [comment]
Thank you for the update. I'm not sure about the exception as I was just running the example code (capture_yuyv.cr) and this happened.
However, I figured out that it rarely just works if I try to run it many times, and the chance of success increases if you lower the format size.

**Comment by postmodern** [comment]
@soya-daizu it could be that your buffers are not big enough for the video frame. `YUYV` formats have fixed width frames (height * width * 4). MJPEG formats have variable length frames due to the JPEG compression of each frame.

**Comment by soya-daizu** [comment]
I tried with different buffer length and buffer count but no luck so far. It only works sometimes if I run it in a row. Now I'm trying it with mmap streaming instread of user pointer streaming, but I'm not sure the right way to do it in Crystal.

**Comment by postmodern** [comment]
@soya-daizu there is a [mmap.cr](https://github.com/crystal-posix/mmap.cr) shard.

**Comment by soya-daizu** [comment]
I'm closing this as the issue in the title is resolved and the latter issue is probably due to my hardware problem. Thanks for the help anyway!
